-- ─── HELPER: auto-update updated_at ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── CUSTOMERS ───────────────────────────────────────────────────────────────
CREATE TABLE customers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text        NOT NULL,
  initials      text        NOT NULL,
  color         text        NOT NULL DEFAULT '#6B6B6B',
  plan          text        NOT NULL CHECK (plan IN ('Starter', 'Pro', 'Business')),
  mrr           integer     NOT NULL DEFAULT 0,
  health_score  integer     NOT NULL DEFAULT 50 CHECK (health_score >= 0 AND health_score <= 100),
  status        text        NOT NULL CHECK (status IN ('Aktiv', 'Gefährdet')),
  renewal_date  date        NOT NULL,
  last_login    date,
  users_count   integer     NOT NULL DEFAULT 0,
  campaigns     integer     NOT NULL DEFAULT 0,
  projects      integer     NOT NULL DEFAULT 0,
  nps           integer     CHECK (nps >= 0 AND nps <= 10),
  industry      text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_customers_status ON customers (status);
CREATE INDEX idx_customers_renewal_date ON customers (renewal_date);

-- ─── CONTACTS ────────────────────────────────────────────────────────────────
CREATE TABLE contacts (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  bigint      NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  name         text        NOT NULL,
  role         text,
  email        text,
  phone        text,
  initials     text        NOT NULL,
  color        text        NOT NULL DEFAULT '#6B6B6B',
  last_contact date,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_contacts_customer_id ON contacts (customer_id);

-- ─── ACTIVITIES ──────────────────────────────────────────────────────────────
CREATE TABLE activities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint      NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  type        text        NOT NULL CHECK (type IN ('email', 'call', 'note', 'system')),
  text        text        NOT NULL,
  user_name   text        NOT NULL,
  initials    text        NOT NULL,
  color       text        NOT NULL DEFAULT '#6B6B6B',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_activities_customer_id ON activities (customer_id);
CREATE INDEX idx_activities_created_at  ON activities (created_at DESC);

-- ─── ONBOARDING ──────────────────────────────────────────────────────────────
CREATE TABLE onboarding (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint      NOT NULL UNIQUE REFERENCES customers (id) ON DELETE CASCADE,
  phase       text        NOT NULL DEFAULT 'Neu',
  steps       jsonb       NOT NULL DEFAULT '[]',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_onboarding_updated_at
  BEFORE UPDATE ON onboarding
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
